### PR TITLE
removed NSO button and menu option

### PR DESCRIPTION
**Pull request by andrewsi10**

### CODE REVIEW

**Comment by adelq** [comment]
Make sure to also remove the unneeded dependencies from the `build.gradle`, which are preventing me from compiling the project ;)

**Comment by jasontsh** [comment]
@adelq is ur computer happy to compile this? LGTM but we need your input

**Comment by adelq** [comment]
Updating Android Studio, will let you know soon

**Comment by adelq** [comment]
LGTM! Awesome job Andrew, I can finally work on Android once more :)

**Pull request merged**
