### PR TITLE
Fix #263

### LINKED ISSUE #263: Next serving not working in dining
Works within the same day but does not carry over to next day's menus

### PR DESCRIPTION
**Pull request by jasontsh**

### CODE REVIEW

**Comment by adelq** [comment]
Please comment this code, I'm having trouble following it. Also, follow the style guidelines and DRY (don't repeat yourself)

**Comment by adelq** [comment]
LGTM

**Comment by adelq** [comment]
@dlakata can you review this?

**Comment by dlakata** [comment]
Reformat the code to fix the spacing in the second for loop. Otherwise, LGTM

**Pull request merged**
